### ISSUE TITLE
ざっくり仕様・イメージを固める

### ISSUE THREAD

**Issue by mono0926** [mono0926/Ice#1]

**Comment by mono0926** [comment]
## コンセプト
- [ブクログ](http://booklog.jp/)・[＠cosme](http://www.cosme.net/)のアイス版
- 利用者の感想がどんどん集まってくる場
  - 利用者いなかったら個人的にメモに使おう（´-ω-｀）

## 対象
- アイス
  - コンビニスイーツ(アイス含む)もありな気がしてきました(　´･‿･｀)

## 競合

今のところ、アイスもコンビニスイーツも無さそう(個人でひたすらレポート書いているのはたくさんあるけど)。  
せっかく作るなら、あわよくば流行るやつにしたい。

需要自体は充分ありそう。
- [コンビニスイーツ - NAVER まとめ](http://matome.naver.jp/topic/1M0Z5)
- [【コンビニの本気】絶対ハマる！絶品コンビニスイーツ・カテゴリ別まとめ - NAVER まとめ](http://matome.naver.jp/odai/2133249103575096201)
- [大変なことになってる最近のコンビニスイーツ厳選１０ - NAVER まとめ](http://matome.naver.jp/odai/2138551896913258501)

## TODO
- [ ] 既存の似たサービスが無いか調査 → すでにあったら全く別の考え直すのもありかも
- [ ] せっかく作っても使ってもらえないと残念だけど何か対策無いかなあ
- [ ] 名前→#5

**Comment by mono0926** [comment]
テーマが合えば、[クックパッド開発コンテスト24](https://info.cookpad.com/24contest4)にも出したいかも。

去年、やぶさんと参加して、残念な結果だったけど[第4回「開発コンテスト24」受賞作品発表 | クックパッド株式会社](https://info.cookpad.com/24contest4_award)に載ってます(　´･‿･｀)
[余命チェッカー | about.me](http://about.me/yomei)

1位の[DECOPOCHI | 誰でも簡単にオリジナルのぽち袋が作れるwebサービス](http://decopochi.com/)は、普通にWebサービスとして今も動いていたり(　´･‿･｀)

今年の開催がまだ発表されてないけど、やるとしたら近々告知があるはず(　´･‿･｀)

**Comment by mono0926** [comment]
## 5月7日(水) 議事録

### [もぐナビ(mognavi) - 食品クチコミサイト](http://s.mognavi.jp/)
- [アイスのクチコミ、ランキング、新商品 | 食品クチコミサイト もぐナビ](http://s.mognavi.jp/icecream)
- 「お菓子 口コミ」「コンビニスイーツ 口コミ」でぐぐると出てくる

### アプリ
- [sweetsdiary(スイーツダイアリー)SNS的な日記カメラ](https://itunes.apple.com/jp/app/sweetsdiary-suitsudaiari-sns/id698468420?mt=8)
  - スイーツSNSなiPhoneアプリ
  - 評価ゼロ件だし、アプリ動かなかった
- あとアプリ無いか探した
  - [コンビニアイスマニア](https://itunes.apple.com/jp/app/konbiniaisumania/id459703836?l=en&mt=8)→ブログがアプリになっただけ
  - [もぐナビ](https://itunes.apple.com/jp/app/mogunabi/id480606094?l=en&mt=8)→mognavもアプリあったけど3.5インチ画面だしWEBの画面表示しているだけのかなり手抜き

### [スイーツ探検隊](http://sns.monteur.co.jp/)
- 2013年3月30日（土）終了
- どんなのだったんだろう
  - [Facebookで活動してる](https://www.facebook.com/monteur.sweets)みたいだけど、基本情報発信型な気がする

### かわいい流行ってるサービスを良い感じにパクりたい
- [mery [メリー] | 女の子の毎日をかわいく。](http://mery.jp/)
- [Fril 女の子のためのフリマアプリ](https://fril.jp/)
- [【UI/UX考察付】デザイナーとして気になる5つの女子向けアプリ | creive【クリーブ】](http://creive.me/archives/4766/)
  - [恋するマップ～女子ちず～](https://itunes.apple.com/jp/app/liansurumappu-nu-zichizu/id786114434?mt=8)
  - [かわいい女子向けコミュニティ"Chatee"](https://itunes.apple.com/jp/app/kawaii-nu-zi-xiangkekomyuniti/id814299565?mt=8&ign-mpt=uo%3D4)
  - [ファッションコーディネート iQON(アイコン) ブランド品からコーデをコラージュして楽しむアプリ](https://itunes.apple.com/jp/app/fasshonkodineto-iqon-aikon/id497264307?mt=8&ign-mpt=uo%3D4)
  - [簡単お買い物計算アプリ「CALFUL」](https://itunes.apple.com/jp/app/jian-dano-maii-wu-ji-suanapuri/id721433214?mt=8&ign-mpt=uo%3D4)
  - [プライベート無料日記 -Livre(リブリ)- 無料で日記、写真、カメラ(写真加工)](https://itunes.apple.com/jp/app/puraibeto-wu-liao-ri-ji-livre/id687207501?mt=8&ign-mpt=uo%3D4)

### その他

> そもそも120円のアイス買うのにいちいちレビュー見ないよね

つらたん

> だったら口コミサイトよりよりSNSの方がいいかも( ´･‿･｀)
> 女の子好きそう( ´･‿･｀)
> みんなスイーツの写真撮りたがるしww

**Comment by nozonozonozono** [comment]
ありがとうございますd( ´･‿･｀)

**Comment by mono0926** [comment]
こちらこそありがとうございます(　´･‿･｀)

**Comment by nozonozonozono** [comment]
グダグダになっちゃいそうなので（私が）、スケジュール決めたいですねー。
あと目標決めたり。クックパッド開発コンテストもテーマがあうといいんだけど。。

**Comment by mono0926** [comment]
一応この「ざっくり作成」マイルストーンで今月までに設定してます(　´･‿･｀)
[Issues · mono0926/Ice](https://github.com/mono0926/Ice/issues?milestone=1&state=open)

僕が勉強サボらない限り、この#1のタスクを固めるのが一番大変そうです（´-ω-｀）

クックパッド開発コンテスト開催発表、去年は今頃だったぽい(　´･‿･｀)
[Twitter / 24contest: 今年も開発コンテスト24を開催します！6/15～16 を空け ...](https://twitter.com/24contest/status/332780815845044224)

**Comment by nozonozonozono** [comment]
ざっくり作成？？

**Comment by mono0926** [comment]
マイルストーン周りの設定項目見づらいんだけど「ざっくり作成」っての作ってあるのです(　´･‿･｀)
https://github.com/mono0926/Ice/issues/milestones

**Comment by nozonozonozono** [comment]
なるほど、ありがとうございます(　´･‿･｀)
